name: Pre-Release-Python (3.10 beta 3)

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: APT Update
      run: sudo apt update

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.10.0-beta.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Pytest
      run: pytest

    - name: Check code with Mypy
      run: |
        pip install mypy
        mypy agg/
